#!/usr/bin/python

# use pygal to build a PNG graph

import sys
import pygal
from datetime import datetime
import time
import MySQLdb as mdb

# open database
try:
  conn = mdb.connect('192.168.1.40', 'bee_sigfox_sync', '', 'beedb')
except:
  sys.stderr.write("DB connect error\n")
  exit(1)

# create db cursor with access to row by name
c = conn.cursor(mdb.cursors.DictCursor)

## process RAW message
sql = ("SELECT"+ 
       "  rx_timestamp, var_min, var_avg, var_max "+
       "FROM sig_stat WHERE object_id = 4 "+
       "ORDER BY rx_timestamp DESC LIMIT 12;")
c.execute(sql)

records = c.fetchall()

sql_datetime = []
sql_c_min    = []
sql_c_avg    = []
sql_c_max    = []

for record in records:
  # convert UTC timestamp to localtime datetime string
  utc_dt = datetime.fromtimestamp(record['rx_timestamp'])
  now_timestamp = time.time()
  offset = (datetime.fromtimestamp(now_timestamp) - 
            datetime.utcfromtimestamp(now_timestamp))
  local_dt = utc_dt + offset
  # add data to lists
  sql_datetime.append(local_dt.strftime ("%Y-%m-%d %H:%M:%S"))
  sql_c_min.append(record['var_min'])
  sql_c_avg.append(record['var_avg'])
  sql_c_max.append(record['var_max'])

# reverse lists order
sql_datetime.reverse()
sql_c_min.reverse()
sql_c_avg.reverse()
sql_c_max.reverse()

# draw SVG
line_chart = pygal.Line()
line_chart.title = ("Lestrem battery average current (+ -> fill, - -> empty) "+
                    "for last 3 hours")
line_chart.x_title = "date and time"
line_chart.y_title = "current (in ma)"
line_chart.x_labels = sql_datetime
line_chart.x_label_rotation = 45
line_chart.add("MIN Current", sql_c_min)
line_chart.add("AVG Current", sql_c_avg)
line_chart.add("MAX Current", sql_c_max)
line_chart.render_to_file('/tmp/lestrem/36h_current.svg')
exit(0)

